export const TODO_ACTIONS = {
  INITIALIZE_TODOS: "INITIALIZE_TODOS",
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
  CHANGE_TODO_TITLE: "CHANGE_TODO_TITLE",
};

export const TODO_LIST_FILTER_ACTIONS = {
  CHANGE_FILTER: "CHANGE_FILTER",
};
